### ISSUE TITLE
couldn't download layout.conf

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [hartwork/fetchcommandwrapper#5] opened 2020-04-29 22:47 UTC
It tries to download layout.conf from every mirror and it fails
```
No digest file available and download failed.

!!! Couldn't download '.layout.conf.ftp.wh2.tu-dresden.de'. Aborting.
>>> Downloading 'ftp://ftp.wh2.tu-dresden.de/pub/mirrors/gentoo/distfiles/texlive-module-luaimagee
mbed-2020.tar.xz'
ERROR: All Gentoo mirrors tried already, exiting.
>>> Downloading 'https://ftp-stud.hs-esslingen.de/pub/Mirrors/gentoo/distfiles/layout.conf'
ERROR: All Gentoo mirrors tried already, exiting.
No digest file available and download failed.

!!! Couldn't download '.layout.conf.ftp-stud.hs-esslingen.de'. Aborting.
>>> Downloading 'https://ftp-stud.hs-esslingen.de/pub/Mirrors/gentoo/distfiles/texlive-module-luai
mageembed-2020.tar.xz'
ERROR: All Gentoo mirrors tried already, exiting.
>>> Downloading 'https://mirror.eu.oneandone.net/linux/distributions/gentoo/gentoo/distfiles/layou
t.conf'
No digest file available and download failed.

!!! Couldn't download '.layout.conf.mirror.eu.oneandone.net'. Aborting.
>>> Downloading 'https://mirror.eu.oneandone.net/linux/distributions/gentoo/gentoo/distfiles/texli
ve-module-luaimageembed-2020.tar.xz'
ERROR: All Gentoo mirrors tried already, exiting.
>>> Downloading 'https://mirror.netcologne.de/gentoo/distfiles/layout.conf'
ERROR: All Gentoo mirrors tried already, exiting.
No digest file available and download failed.

!!! Couldn't download '.layout.conf.mirror.netcologne.de'. Aborting.
>>> Downloading 'https://mirror.netcologne.de/gentoo/distfiles/texlive-module-luaimageembed-2020.t
ar.xz'
ERROR: All Gentoo mirrors tried already, exiting.
>>> Downloading 'https://ftp.halifax.rwth-aachen.de/gentoo/distfiles/layout.conf'
ERROR: All Gentoo mirrors tried already, exiting.
No digest file available and download failed.

!!! Couldn't download '.layout.conf.ftp.halifax.rwth-aachen.de'. Aborting.
>>> Downloading 'https://ftp.halifax.rwth-aachen.de/gentoo
```

**Comment by hartwork** [comment] 2020-04-29 22:56
Hi! I have not had a closer look at this yet. For a quick reply: How did you make it download `layout.conf` and what do you have in mind for a fix?

**Comment by Alessandro-Barbieri** [comment] 2020-04-30 02:09
I think it download layout.conf because of this https://www.gentoo.org/glep/glep-0075.html
wget instead seems to download them without problems

**Comment by hartwork** [comment] 2020-04-30 18:13
Can you help out with a complete command line to understand why or how emerge fetchcommandwrapper is called here? Also can you share the output of `portageq envvar GENTOO_MIRRORS`? I'll need more info to be able to understand and fix an potential issue here.

**Comment by Alessandro-Barbieri** [comment] 2020-04-30 19:02
I had run `emerge texlive-latexextra` (it doesn't matter) and in another terminal `tail -f /var/log/emerge-fetch.log`

I also copied `/usr/share/fetchcommandwrapper/make.conf` as `/etc/portage/make.conf/fetchcommandwrapper.conf`

```
portageq envvar GENTOO_MIRRORS
ftp://ftp.fi.muni.cz/pub/linux/gentoo/ ftp://gentoo.mirror.web4u.cz/ https://mirror.dkm.cz/gentoo/ http://gentoo.mirrors.ovh.net/gentoo-distfiles/ ftp://ftp.free.fr/mirrors/ftp.gentoo.org/ https://mirrors.soeasyto.com/distfiles.gentoo.org/ http://gentoo.modulix.net/gentoo/ https://linux.rz.ruhr-uni-bochum.de/download/gentoo-mirror/ https://ftp.fau.de/gentoo ftp://ftp.wh2.tu-dresden.de/pub/mirrors/gentoo https://ftp-stud.hs-esslingen.de/pub/Mirrors/gentoo/ https://mirror.eu.oneandone.net/linux/distributions/gentoo/gentoo/ https://mirror.netcologne.de/gentoo/ https://ftp.halifax.rwth-aachen.de/gentoo/ ftp://ftp.ntua.gr/pub/linux/gentoo/ https://mirrors.evowise.com/gentoo/ https://mirror.leaseweb.com/gentoo/ https://ftp.snt.utwente.nl/pub/os/linux/gentoo ftp://ftp.vectranet.pl/gentoo/ https://ftp.rnl.tecnico.ulisboa.pt/pub/gentoo/gentoo-distfiles/ ftp://ftp.dei.uc.pt/pub/linux/gentoo/ http://mirrors.xservers.ro/gentoo/ http://ftp.romnet.org/gentoo/ https://mirror.mdfnet.se/gentoo https://gentoo.wheel.sk/ ftp://tux.rainside.sk/gentoo/ https://mirrors.evowise.com/gentoo/ https://mirror.bytemark.co.uk/gentoo/ https://www.mirrorservice.org/sites/distfiles.gentoo.org/ https://mirror.yandex.ru/gentoo-distfiles/ https://gentoo-mirror.alexxy.name/ ftp://gentoo.bloodhost.ru/
```

**Comment by hartwork** [comment] 2020-04-30 19:11
It worked for me:

```console
# cd /usr/portage/dev-vcs/svneverever/
# ebuild svneverever-1.5.0.ebuild fetch              
Appending [..] to PORTDIR_OVERLAY...
>>> Downloading 'http://ftp.spline.inf.fu-berlin.de/mirrors/gentoo/distfiles/layout.conf'
fetchcommandwrapper 0.8.3

URI = http://ftp.spline.inf.fu-berlin.de/mirrors/gentoo/distfiles/layout.conf
DISTDIR = /usr/portage/distfiles
FILE = .layout.conf.ftp.spline.inf.fu-berlin.de.__download__

Involved mirrors:
  - http://ftp.spline.inf.fu-berlin.de/mirrors/gentoo/
  - http://ftp-stud.hs-esslingen.de/pub/Mirrors/gentoo/
  - http://ftp.uni-erlangen.de/pub/mirrors/gentoo/
  - http://ftp.halifax.rwth-aachen.de/gentoo/
  - http://linux.rz.ruhr-uni-bochum.de/download/gentoo-mirror/
  - ftp://ftp.wh2.tu-dresden.de/pub/mirrors/gentoo/
  - ftp://sunsite.informatik.rwth-aachen.de/pub/Linux/gentoo/
  - ftp://ftp.tu-clausthal.de/pub/linux/gentoo/
  (8 mirrors)

Targetting 5 random connections, additional 3 for backup

Running... # /usr/bin/aria2c -d /usr/portage/distfiles -o .layout.conf.ftp.spline.inf.fu-berlin.de.__download__ --lowest-speed-limit=436906 --allow-overwrite=true --max-tries=5 --max-file-not-found=2 --user-agent=Wget/1.19.1 --split=5 --max-connection-per-server=1 --uri-selector=inorder --follow-metalink=mem ftp://ftp.wh2.tu-dresden.de/pub/mirrors/gentoo/distfiles/layout.conf http://ftp.uni-erlangen.de/pub/mirrors/gentoo/distfiles/layout.conf http://ftp.spline.inf.fu-berlin.de/mirrors/gentoo/distfiles/layout.conf http://ftp-stud.hs-esslingen.de/pub/Mirrors/gentoo/distfiles/layout.conf http://linux.rz.ruhr-uni-bochum.de/download/gentoo-mirror/distfiles/layout.conf ftp://ftp.tu-clausthal.de/pub/linux/gentoo/distfiles/layout.conf http://ftp.halifax.rwth-aachen.de/gentoo/distfiles/layout.conf ftp://sunsite.informatik.rwth-aachen.de/pub/Linux/gentoo/distfiles/layout.conf

04/30 21:04:44 [NOTICE] Downloading 1 item(s)

04/30 21:04:45 [NOTICE] Download complete: /usr/portage/distfiles/.layout.conf.ftp.spline.inf.fu-berlin.de.__download__

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
ea0912|OK  |     750B/s|/usr/portage/distfiles/.layout.conf.ftp.spline.inf.fu-berlin.de.__download__

Status Legend:
(OK):download completed.
[..]
```

**Comment by hartwork** [comment] 2020-04-30 19:30
I guess we're dealing with this thing:
https://gitweb.gentoo.org/proj/portage.git/tree/lib/portage/package/ebuild/fetch.py#n479

What do you think about checking for the URL ending in `'/distfiles/layout.conf'` and not using any mirrors in that case but the original URL, only?

**Comment by Alessandro-Barbieri** [comment] 2020-04-30 19:55
yes, something like https://gitweb.gentoo.org/proj/portage.git/tree/lib/portage/package/ebuild/fetch.py#n507 can possibly work

**Comment by hartwork** [comment] 2020-04-30 20:12
This issue is addressed on `master` since 73da6120e4bdd69eefd0b63affa2b82723e7e0c3 now. What do you think?

**Comment by Alessandro-Barbieri** [comment] 2020-04-30 20:34
I have tried it but now it is stuck when fetching the layout.conf

**Comment by Alessandro-Barbieri** [comment] 2020-04-30 20:35
Also I found out that `tail -f /var/log/emerge-fetch.log` is useful only when fetching files for more than one package. For only one package you need to watch it using `emerge --jobs=1 package`

**Comment by hartwork** [comment] 2020-04-30 21:36
> I have tried it but now it is stuck when fetching the layout.conf

Could you elbarote? Can you rule out a bad mirror and try the very URL with both fetchcommandwrapper and wget?

**Comment by Alessandro-Barbieri** [comment] 2020-05-05 21:34
I tried `fetchcommandwrapper https://mirrors.soeasyto.com/distfiles.gentoo.org/distfiles/0e/tl-abstract-2020.tar.xz /home/ale tl-abstract-2020.tar.xz`

**Comment by hartwork** [comment] 2020-05-05 21:49
I don't get it

**Comment by Alessandro-Barbieri** [comment] 2020-05-07 01:46
Ok, for reproducibility I have downloaded a stage3, unpacked, chrooted, installed fetchcommandwrapper, added the mirrors and it's conf to make.conf.
Now I tried to emerge something `texlive-latexextra`, at first it downloaded some files fine, then it stuck.

**Comment by hartwork** [comment] 2020-05-07 20:33
Did you install from Git or through emerge?

**Comment by Alessandro-Barbieri** [comment] 2020-05-08 00:29
This time with emerge, a 9999 version will be useful

**Comment by hartwork** [comment] 2020-05-08 13:54
Well, with no fix released the emerged version has got to be broken, right?
I'll close this ticket and make a release, this is going nowhere and my patience is at zero by now.

**Closed by hartwork** 2020-05-08 13:54 UTC

**Comment by hartwork** [comment] 2020-05-08 14:04
0.8.4 has just hit PyPI and Gentoo now.

**Comment by Alessandro-Barbieri** [comment] 2020-05-08 22:53
Have you tried to reproduce it the way I have shown you?
I also find out the reason of the mirror stuck, it's caused by bad mirrors and I removed it from the list

**Comment by hartwork** [comment] 2020-05-10 14:12
You can tell fetchcommandwrapper about the speed of your link to the internet using `--link-speed SPEED` and it will make aria2c drop connections that are below a certain speed (formula `int(opts.link_speed_bytes / wanted_connections / 3)`. That may help against some slow or stuck mirrors.

**Comment by Alessandro-Barbieri** [comment] 2020-05-10 18:14
I asked in a group to help reproduce the issue and they got this
https://pastebin.com/NfuJbpJq

**Comment by hartwork** [comment] 2020-05-10 19:11
If http://tux.rainside.sk/gentoo/ is as empty as it is it's not wonder that `distfiles/layout.conf` cannot be downloaded from that mirror. If you want me to fix something more, I'll need something reproducable that is not caused by the mirror itself.
